// PLACEHOLDER DATA — replace with real Executive Committee information.
export const executiveCommittee = [
  {
    id: 1,
    name: "Md. Rakibul Hasan",
    position: "President",
    department: "Department of English",
    session: "2020-21",
    photo: "https://i.pravatar.cc/300?img=12",
    bio: "Leads the club's strategic direction and represents JKKNIU Chess Club at inter-university forums.",
    facebook: "#", email: "president@jkkniuchess.club",
  },
  {
    id: 2,
    name: "Fahmida Islam Mou",
    position: "Vice President",
    department: "Department of Sociology",
    session: "2020-21",
    photo: "https://i.pravatar.cc/300?img=32",
    bio: "Oversees committee operations and coordinates with department representatives.",
    facebook: "#", email: "vp@jkkniuchess.club",
  },
  {
    id: 3,
    name: "Sadman Anik",
    position: "General Secretary",
    department: "Department of CSE",
    session: "2021-22",
    photo: "https://i.pravatar.cc/300?img=15",
    bio: "Manages day-to-day club administration, correspondence and member records.",
    facebook: "#", email: "gs@jkkniuchess.club",
  },
  {
    id: 4,
    name: "Tania Rahman",
    position: "Joint General Secretary",
    department: "Department of Economics",
    session: "2021-22",
    photo: "https://i.pravatar.cc/300?img=45",
    bio: "Assists the General Secretary and manages member communication.",
    facebook: "#", email: "jgs@jkkniuchess.club",
  },
  {
    id: 5,
    name: "Imran Kabir",
    position: "Treasurer",
    department: "Department of Accounting",
    session: "2021-22",
    photo: "https://i.pravatar.cc/300?img=18",
    bio: "Handles club finances, membership fees and tournament budgets.",
    facebook: "#", email: "treasurer@jkkniuchess.club",
  },
  {
    id: 6,
    name: "Nusrat Jahan Priya",
    position: "Organizing Secretary",
    department: "Department of Public Administration",
    session: "2022-23",
    photo: "https://i.pravatar.cc/300?img=47",
    bio: "Plans and executes tournaments, workshops and club events.",
    facebook: "#", email: "organizing@jkkniuchess.club",
  },
  {
    id: 7,
    name: "Shakil Ahmed",
    position: "IT & Communications Secretary",
    department: "Department of CSE",
    session: "2022-23",
    photo: "https://i.pravatar.cc/300?img=51",
    bio: "Maintains the club website, social media pages and online registrations.",
    facebook: "#", email: "it@jkkniuchess.club",
  },
  {
    id: 8,
    name: "Ruma Akter",
    position: "Publication & Documentation Secretary",
    department: "Department of Bangla",
    session: "2022-23",
    photo: "https://i.pravatar.cc/300?img=26",
    bio: "Prepares newsletters, reports and archival documentation of club activities.",
    facebook: "#", email: "publication@jkkniuchess.club",
  },
  {
    id: 9,
    name: "Tanvir Hossain",
    position: "Logistics & Equipment Secretary",
    department: "Department of Physics",
    session: "2022-23",
    photo: "https://i.pravatar.cc/300?img=60",
    bio: "Manages chess sets, clocks, boards and venue arrangements.",
    facebook: "#", email: "logistics@jkkniuchess.club",
  },
];

export const executiveMembers = [
  { id: 10, name: "Arifin Chowdhury", position: "Executive Member", department: "Department of Law", session: "2022-23", photo: "https://i.pravatar.cc/300?img=33" },
  { id: 11, name: "Mahin Sarker", position: "Executive Member", department: "Department of Statistics", session: "2022-23", photo: "https://i.pravatar.cc/300?img=14" },
  { id: 12, name: "Farzana Yasmin", position: "Executive Member", department: "Department of Botany", session: "2022-23", photo: "https://i.pravatar.cc/300?img=20" },
  { id: 13, name: "Rezwan Islam", position: "Executive Member", department: "Department of History", session: "2022-23", photo: "https://i.pravatar.cc/300?img=8" },
];

export const formerCommittees = [
  { year: "2023-2024", president: "Md. Nayeem Hasan", generalSecretary: "Sabrina Alam" },
  { year: "2022-2023", president: "Kazi Fahim", generalSecretary: "Lubna Tasnim" },
  { year: "2021-2022", president: "Asif Rahman", generalSecretary: "Mim Akter" },
];
